version: '3.8'

services:
  renfe-bot:
    build: .
    container_name: renfe-bot
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN:-}
      - ALLOWED_USER_ID=${ALLOWED_USER_ID:-}
